version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

